### ISSUE TITLE
Publish mock-okta?

### ISSUE THREAD

**Issue by wprl** [okta/samples-python-flask#11]
I found the mock-okta tool in this repo to be very useful for testing.  Are there any plans to publish a version to npm?

**Comment by robertjd** [comment]
Hi @wprl , thanks for the question.  The version you see in this library is a bit outdated, we've actually moved our testing and mocking efforts here:

https://github.com/okta/okta-oidc-tck/

Since it's now a Java project there is an artifact available in Maven, which you can see us using here:

https://github.com/okta/okta-oidc-js/blob/master/packages/oidc-middleware/package.json#L17

I hope this helps!

**Comment by wprl** [comment]
OK thanks!
