### ISSUE TITLE
How can we "fully" logout the user such that credentials are required to log back in ?

### ISSUE THREAD

**Issue by Ayushi96** [okta/samples-python-flask#27]
I tried to runt the okta-hosted-login and once the user logs in, no credentials are required to log back in even after a log-out. Is there any function supported by flask-oidc to fully log out the user?

**Comment by bretterer** [comment]
Currently, Logging out of the okta-hosted-login removes local application tokens. The reason you didn't have to log back in is because the logout process does not log you out from Okta. I believe what you are looking for is our [revoking a token endpoint](https://developer.okta.com/docs/reference/api/oidc/#revoke)

As for integration with flask-oidc, we do not have any support built in. The samples here are a jumping off point to show you the basics of authentication using python and flask so we don't go into anything further yet around all the use cases.

**Comment by serhiibuniak-okta** [comment]
I'm closing this issue as it looks like stalled. @Ayushi96 feel free to reopen or create a new issue if you need some help with samples.
