### ISSUE TITLE
Clarification on the PKCE based approach - Pyhton

### ISSUE THREAD

**Issue by kamalmobiledev** [okta/samples-python-flask#63]
Hi team,

We are evaluating options for PKCE integration into our Python Flask based web app. However we could see there are documentations on the Python based samples for this approach. 

If we opt in via the suggested  examples in the repo is Client Secret mandatory for the same ?https://github.com/okta/samples-python-flask

Please suggest.

**Comment by kamalmobiledev** [comment]
Also the note in this repo say "These examples require the use of API Access Management. This solution is not included by default for organizations (you will have this error)."  Can you please provide us the steps for enabling and verifying the same.

**Comment by serhiibuniak-okta** [comment]
@kamalmobiledev Do you mean option `"client_secret": "{{CLIENT_SECRET}}"` from `client_secrets.json`? For PKCE flow it is not needed. We don't have flask sample for PKCE flow.

regarding API Access Management:
1. If you can't try these examples because of that error, this means org is missing "API Access Management" SKU, contact your Okta account executive to discuss your account.
2. If you do not know who your account executive is, contact Okta support

**Comment by kamalmobiledev** [comment]
@serhiibuniak-okta Thanks for the response. Are there any steps of how to enable API Access Management via the admin dev console ?

**Comment by serhiibuniak-okta** [comment]
@kamalmobiledev some of the features can be enabled here `{your_org_url}/admin/settings/features`, but this one, probably, via support only.

**Comment by serhiibuniak-okta** [comment]
@kamalmobiledev I'm closing this issue as resolved. Feel free to reopen this issue or create a new one if your problem exists still.
